### ISSUE TITLE
Small problem with routeProvider.

### ISSUE THREAD

**Issue by globsecure** [trochette/Angular-Design-Patterns-Best-Practices#17]
Problem with $routeProvider add routes for HomeController:

.when('/home', {
                templateUrl: 'build/views/home/index.html',
                controller: 'HomeController'
            })

Error:

Error: [ng:areq] http://errors.angularjs.org/1.4.7/ng/areq?p0=HomeController&p1=not%20aNaNunction%2C%20got%20undefined

**Comment by Ed64rd0** [comment]
did you import the HomeController?? something like this:

var test = angular.module('testApp', ['ngRoute', 'homeCtrl']);

**Comment by globsecure** [comment]
@Ed64rd0 

Thanks for the reply, following code developed using the idea of the project.

Link basic code:
http://pastebin.com/C2i0xFyH
