### ISSUE TITLE
THE ANIMATION ONE EACH AND EVERY PAGE IS EXTREMELY ANNOYING

### ISSUE THREAD

**Issue by ziffusion** [trochette/Angular-Design-Patterns-Best-Practices#18]
It's pretty, yes. But please, I beg you, please take away this inhumane torture. Give us a more usable navigation.

How old is the person who came up with this idea anyways?!

**Comment by trochette** [comment]
Thanks for your feedback. This was built a couple years ago, when I was presenting at MagmaConf and this was serving as my keynote. Feel free to fork or create a pull request that change / improve the speed of the animation
