### ISSUE TITLE
Justification/Further explanation of design patterns

### ISSUE THREAD

**Issue by yintothayang** [trochette/Angular-Design-Patterns-Best-Practices#7]
Hi Tommy, couldn't find an email anywhere so this is the only way I could seem to talk to you. 

Could you explain how, I could get the "slides" in the NotesModel into $scope to be bound to an attribute in the html? I don't understand how to get objects in the Model into $scope to be bound to ng-attributes. 

Also why does NotesModel inherit from EventDispatcher?  

I really like the ideas you present here, you solve complex controller interactions elegantly. It seems like you have used ReactJS before, as these Angular modules are starting to look like React components! Love the reusability in the Model and Service providers. 

If would rather talk via email i'm at yintothayang@gmail.com 

Thanks a bunch in advance, 

Yin

**Comment by moneytree-doug** [comment]
@yintothayang I have similar questions, did you ever get a reply? Would you mind sharing?

**Comment by yintothayang** [comment]
I never received a reply, he looks busy with Apple stuff now. 

Regardless, I think i've got the paradigms down now,  checkout: https://github.com/MakoWare/Dojo/blob/UIrefactor/parse/public/new/components/contacts/contactList.js

When one of your models gets data (probably from a service) fire a notifications.notify() event. On your  controller in defineListeners() add the appropriate event listener. When that event handler is called then put the data you need from your model into the $scope. If you have anymore questions let me know.

**Comment by moneytree-doug** [comment]
That link 404ed

**Comment by yintothayang** [comment]
sorry, stuff has been moving
https://github.com/MakoWare/Dojo/blob/UIrefactor/parse/public/components/contact/contactList.js
